USE ecommerce_analytics;

-- 1. Display all customers
SELECT * 
FROM customers;


-- 2. Count total customers
SELECT COUNT(*) AS total_customers
FROM customers;


-- 3. Count total orders
SELECT COUNT(*) AS total_orders
FROM orders;


-- 4. Find the highest-priced product
SELECT product_name, category, price
FROM products
ORDER BY price DESC
LIMIT 1;


-- 5. Find the average product price
SELECT ROUND(AVG(price), 2) AS average_product_price
FROM products;


-- 6. Find total quantity sold for each product
SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status <> 'Cancelled'
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC;


-- 7. Calculate revenue generated by each product
SELECT
    p.product_name,
    SUM(oi.quantity * p.price) AS revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status <> 'Cancelled'
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC;


-- 8. Revenue by category
SELECT
    p.category,
    SUM(oi.quantity * p.price) AS category_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status <> 'Cancelled'
GROUP BY p.category
ORDER BY category_revenue DESC;


-- 9. Find customer spending
SELECT
    c.customer_name,
    ROUND(SUM(oi.quantity * p.price), 2) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.order_status <> 'Cancelled'
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spending DESC;


-- 10. Find customers who placed more than one order
SELECT
    c.customer_name,
    COUNT(o.order_id) AS number_of_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > 1;


-- 11. Find customers who have not placed any order
SELECT
    c.customer_name,
    c.city
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


-- 12. Count orders by status
SELECT
    order_status,
    COUNT(*) AS number_of_orders
FROM orders
GROUP BY order_status;


-- 13. Find city-wise customer count
SELECT
    city,
    COUNT(*) AS customer_count
FROM customers
GROUP BY city
ORDER BY customer_count DESC;


-- 14. Calculate total revenue
SELECT
    ROUND(SUM(oi.quantity * p.price), 2) AS total_revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status <> 'Cancelled';


-- 15. Find the best-selling product
SELECT
    p.product_name,
    SUM(oi.quantity) AS quantity_sold
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status <> 'Cancelled'
GROUP BY p.product_id, p.product_name
ORDER BY quantity_sold DESC
LIMIT 1;